### ISSUE TITLE
Illegal

### ISSUE THREAD

**Issue by Rxxxin** [PaceCodes/AresClient#1]
I hope you know to leak a client is illegal

**Comment by PaceCodes** [comment]
Send me the client's license, and for you're kind info this client was first on OMA's GitHub and the complete credit goes to him. If there is a client license send me it on this issue.

**Comment by Rxxxin** [comment]
Bro im the dev of the client

**Comment by PaceCodes** [comment]
lmaooo

**Comment by PaceCodes** [comment]
Contact me on my discord: Pace.#0001
*don't forget the . at the end of name cuz 'Pace#0001" is taken by someone*
